### PR TITLE
precompile and add module's docstring

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Doesn't the module docstring already default to the package README?

**Comment by mforets** [comment]
@acroy What about this? The module's docstring can be removed, as it was suggested, but can we add the  `__precompile__` flag? The reason is that julia sometimes complains if you want to precompile a module which depends on another one which is not precompiled.

**Comment by ChrisRackauckas** [comment]
This should be precompiled for sure.

**Comment by acroy** [comment]
I will just merge it as it is. The doc-string can later be removed or adjusted.

**Pull request merged**
